import {
  Bus,
  Castle,
  Drum,
  GraduationCap,
  Hamburger,
  Hospital,
  Landmark,
  Phone,
  Recycle,
  Store,
} from "lucide-react";
import { Amenity, AmenityClasses } from "./types";

export const POIS_PER_RADIUS = 100;

export const amenityClasses: AmenityClasses = {
  healthcareAmenityClasses: {
    classes: [
      Amenity.BabyHatch,
      Amenity.Clinic,
      Amenity.Dentist,
      Amenity.Doctors,
      Amenity.Hospital,
      Amenity.NursingHome,
      Amenity.Pharmacy,
      Amenity.Veterinary,
    ],
    icon: Hospital,
  },
  foodAndDrinkAmenityClasses: {
    classes: [
      Amenity.Bar,
      Amenity.Biergarten,
      Amenity.Cafe,
      Amenity.FastFood,
      Amenity.FoodCourt,
      Amenity.IceCream,
      Amenity.Pub,
      Amenity.Restaurant,
    ],
    icon: Hamburger,
  },
  educationAmenityClasses: {
    classes: [
      Amenity.College,
      Amenity.DrivingSchool,
      Amenity.Kindergarten,
      Amenity.LanguageSchool,
      Amenity.Library,
      Amenity.MusicSchool,
      Amenity.School,
      Amenity.University,
    ],
    icon: GraduationCap,
  },
  transportAmenityClasses: {
    classes: [
      Amenity.BicycleParking,
      Amenity.BicycleRental,
      Amenity.BusStation,
      Amenity.CarRental,
      Amenity.CarSharing,
      Amenity.CarWash,
      Amenity.ChargingStation,
      Amenity.FerryTerminal,
      Amenity.Fuel,
      Amenity.Parking,
      Amenity.Taxi,
    ],
    icon: Bus,
  },
  financialAmenityClasses: {
    classes: [Amenity.ATM, Amenity.Bank, Amenity.BureauDeChange],
    icon: Landmark,
  },
  entertainmentAmenityClasses: {
    classes: [
      Amenity.ArtsCentre,
      Amenity.Casino,
      Amenity.Cinema,
      Amenity.CommunityCentre,
      Amenity.ConferenceCentre,
      Amenity.EventsVenue,
      Amenity.Nightclub,
      Amenity.Planetarium,
      Amenity.SocialCentre,
      Amenity.Studio,
      Amenity.Theatre,
    ],
    icon: Drum,
  },
  publicServiceAmenityClasses: {
    classes: [
      Amenity.Courthouse,
      Amenity.Embassy,
      Amenity.FireStation,
      Amenity.Police,
      Amenity.PostBox,
      Amenity.PostOffice,
      Amenity.Prison,
      Amenity.RangerStation,
      Amenity.RescueStation,
      Amenity.Townhall,
    ],
    icon: Castle,
  },
  facilityAmenityClasses: {
    classes: [
      Amenity.Bench,
      Amenity.Clock,
      Amenity.DrinkingWater,
      Amenity.Fountain,
      Amenity.Shelter,
      Amenity.Telephone,
      Amenity.Toilets,
      Amenity.WasteBasket,
    ],
    icon: Phone,
  },
  wasteManagementAmenityClasses: {
    classes: [
      Amenity.Recycling,
      Amenity.WasteDisposal,
      Amenity.WasteTransferStation,
    ],
    icon: Recycle,
  },
  otherAmenityClasses: {
    classes: [
      Amenity.AnimalShelter,
      Amenity.Crematorium,
      Amenity.DiveCentre,
      Amenity.DogPark,
      Amenity.FuneralHall,
      Amenity.Marketplace,
      Amenity.PlaceOfWorship,
      Amenity.PublicBath,
      Amenity.PublicBookcase,
      Amenity.Shower,
      Amenity.SwimmingPool,
      Amenity.WaterPoint,
    ],
    icon: Store,
  },
};
